env:
  - GO111MODULE=on

gomod:
  proxy: true

builds:
  - skip: false

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs"
      - "^test"

release:
  footer: |
    **Full Changelog**: https://github.com/goreleaser/goreleaser/compare/{{ .PreviousTag }}...{{ .Tag }}
