name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Go Vet
      run: go vet ./...
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        go get -u github.com/goreleaser/goreleaser
        goreleaser release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}